
import javax.swing.JOptionPane;

/**
 *
 * @author emil
 */
public class convertir extends javax.swing.JFrame {

        double numero1 = 0;
        double numero2 = 0;
        double resultadoSuma = 0;
        double resultadoconvercion =0;
       
        double dolar = 0.041;
        double euro = 0.036;
        double cordoba = 1.35;
        double quetzal = 0.31;
        double yen = 4.51;
        
    public convertir() {
        initComponents();
        
        //Inicializar variables
    
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        edt_valor = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        resultado = new javax.swing.JTextField();
        BTN_Convertir = new javax.swing.JButton();
        Combo_Moneda = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ConvertidorDeMonedas");

        jLabel2.setText("Converor de moneda");

        jLabel3.setText("Ingrese el valor a convertir en Lps:");

        jLabel5.setText("Resultado");

        BTN_Convertir.setText("Convertir");
        BTN_Convertir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN_ConvertirActionPerformed(evt);
            }
        });

        Combo_Moneda.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {" ","Dollar", "Euro","Quetzal","Cordoba","Yen" }));

        jLabel6.setText("Seleccione la moneda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(edt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addGap(70, 70, 70)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(resultado)
                            .addComponent(Combo_Moneda, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(31, 31, 31))
            .addComponent(BTN_Convertir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(edt_valor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Combo_Moneda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(resultado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(BTN_Convertir, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //
    private void BTN_ConvertirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN_ConvertirActionPerformed
    /*
        numero1 = Integer.parseInt(this.num1.getText());
        numero2 = Integer.parseInt(this.num2.getText());
        resultadoSuma = numero1 + numero2;
        this.resultado.setText(String.valueOf(resultadoSuma));
        
        
        switch(expression) {
        case x:
        // code block
        break;
        case y:
        // code block
        break;
        default:
        // code block
        }
    */
       //Codigo que se ejecuta al accionar el botonConvertir
       
       
       switch(Combo_Moneda.getSelectedIndex()){
           case 1:
           //Cuando es dollar
             numero1 = Double.parseDouble(this.edt_valor.getText());  
             resultadoconvercion = numero1 * dolar ;
             this.resultado.setText(String.valueOf(resultadoconvercion));
             break;   
           
           case 2:
           //Cuando es Euro 
             numero1 = Double.parseDouble(this.edt_valor.getText());  
             resultadoconvercion = numero1 * euro ;
             this.resultado.setText(String.valueOf(resultadoconvercion));   
            break;
           
           case 3:
           //Quetzal
             numero1 = Double.parseDouble(this.edt_valor.getText());  
             resultadoconvercion = numero1 * quetzal ;
             this.resultado.setText(String.valueOf(resultadoconvercion));  
           
           break;
           
           case 4:
           //Cuando es cordoba    
             numero1 = Double.parseDouble(this.edt_valor.getText());  
             resultadoconvercion = numero1 * cordoba ;
             this.resultado.setText(String.valueOf(resultadoconvercion));
           break;
           
           case 5:
           // Cuando es Yen    
             numero1 = Double.parseDouble(this.edt_valor.getText());  
             resultadoconvercion = numero1 * yen ;
             this.resultado.setText(String.valueOf(resultadoconvercion)); 
           break;
           default:
                             
       }   
       
    

        // TODO add your handling code here:
    }//GEN-LAST:event_BTN_ConvertirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(convertir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(convertir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(convertir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(convertir.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new convertir().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN_Convertir;
    private javax.swing.JComboBox<String> Combo_Moneda;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JTextField edt_valor;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JTextField resultado;
    // End of variables declaration//GEN-END:variables
}
